"""
Docs staleness check — single source of truth for "is GUARDIAN_WIKI.md stale".

Reads the `guardian:commit=<sha>` marker `wiki_builder.build_wiki` embeds
into the generated wiki, compares it against the repo's current `HEAD`, and
reports how many commits behind the wiki is. Both the CLI `docs-status`
subcommand and the `guardian://docs-status/{path}` MCP resource wrap this
function rather than reimplementing the check.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

COMMIT_MARKER_RE = re.compile(r"<!--\s*guardian:commit=([0-9a-fA-F]+)\s*-->")


class StalenessCheckError(Exception):
    """Raised when staleness can't be computed (e.g. no wiki generated yet)."""


@dataclass(frozen=True)
class StalenessResult:
    stale: bool
    commits_behind: int
    recorded_sha: str
    head_sha: str


def _git(repo_path: Path, *args: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo_path), *args],
            capture_output=True,
            text=True,
            check=True,
        )
    except subprocess.CalledProcessError as exc:
        raise StalenessCheckError(
            f"git {' '.join(args)} failed for {repo_path}: {exc.stderr.strip()}"
        ) from exc
    return result.stdout.strip()


def check_staleness(repo_path: Path, wiki_path: Path) -> StalenessResult:
    """Compare the SHA embedded in `wiki_path` against `repo_path`'s `HEAD`.

    Raises:
        StalenessCheckError: `wiki_path` doesn't exist or has no embedded
            `guardian:commit=` marker (i.e. it predates this feature or was
            never generated by `dev-guardian docs`).
    """
    if not wiki_path.exists():
        raise StalenessCheckError(
            f"No wiki found at {wiki_path}. Run `dev-guardian docs` first."
        )

    content = wiki_path.read_text(encoding="utf-8")
    match = COMMIT_MARKER_RE.search(content)
    if not match:
        raise StalenessCheckError(
            f"{wiki_path} has no `guardian:commit=` marker. "
            "Regenerate it with `dev-guardian docs`."
        )
    recorded_sha = match.group(1)

    head_sha = _git(repo_path, "rev-parse", "HEAD")

    if recorded_sha == head_sha:
        return StalenessResult(
            stale=False, commits_behind=0, recorded_sha=recorded_sha, head_sha=head_sha
        )

    commits_behind = int(_git(repo_path, "rev-list", "--count", f"{recorded_sha}..{head_sha}"))
    return StalenessResult(
        stale=commits_behind > 0,
        commits_behind=commits_behind,
        recorded_sha=recorded_sha,
        head_sha=head_sha,
    )
