"""
Wiki Builder — Phase 5.3: Auto-Generating Dynamic Documentation.

Orchestrates mermaid_generator and adr_generator into a single
comprehensive markdown wiki document (GUARDIAN_WIKI.md).

This module is the top-level entrypoint for the `guardian docs` command.
It assembles:
  1. Repo summary header.
  2. Module-level dependency flowchart (Mermaid).
  3. Class inheritance hierarchy (Mermaid).
  4. Top-N function call graphs (Mermaid).
  5. Top-N ADRs (Groq-narrated, MADR-style).
"""

import datetime
from pathlib import Path

from groq import Groq

from dev_guardian.core.config import get_settings
from dev_guardian.core.logging import get_logger
from dev_guardian.docs.adr_generator import generate_adr, get_top_complex_nodes
from dev_guardian.docs.structure_explainer import (
    explain_call_graph,
    explain_class_hierarchy,
    explain_module_dependencies,
)
from dev_guardian.graphrag.memgraph_client import MemgraphClient

logger = get_logger(__name__)


def build_wiki(
    repo_path: Path,
    mg: MemgraphClient,
    groq_client: Groq,
    top_n: int = 5,
    user_clearance: int = 0,
) -> str:
    """
    Build a complete markdown wiki for a repository from Memgraph data.

    Orchestrates all three generators into a structured document.
    No re-parsing of source code is required — all data comes from Memgraph.

    Args:
        repo_path: Root of the indexed repository.
        mg: Active MemgraphClient.
        groq_client: Initialized Groq client for ADR narration.
        top_n: Number of high-complexity functions to document.
        user_clearance: ABAC clearance level.

    Returns:
        Complete wiki markdown string.
    """
    timestamp = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%d %H:%M UTC"
    )
    sections = [
        f"# 📖 Guardian Wiki: `{repo_path.name}`\n",
        f"> Auto-generated by **Agentic Dev Guardian** on {timestamp}  \n"
        f"> Source: Live Memgraph AST graph for `{repo_path}`\n\n---\n",
    ]

    # ── 1. Architectural Overview ──────────────────────────────────
    logger.info("wiki_explaining_module_dependencies")
    sections.append("## 🗺️ Architectural Overview\n")
    sections.append(
        "_AI-narrated summary of inter-module relationships derived from Memgraph._\n\n"
        + explain_module_dependencies(repo_path, mg, groq_client, user_clearance)
        + "\n\n---\n"
    )

    # ── 2. Object-Oriented Hierarchy ────────────────────────────────────────
    logger.info("wiki_explaining_class_hierarchy")
    sections.append("## 🏛️ Object-Oriented Hierarchy\n")
    sections.append(
        "_AI-narrated structural analysis of inherited classes._\n\n"
        + explain_class_hierarchy(repo_path, mg, groq_client, user_clearance)
        + "\n\n---\n"
    )

    # ── 3. Top-N Complexity Analysis + Call Graphs ────────────────
    logger.info("wiki_building_call_graphs", top_n=top_n)
    top_nodes = get_top_complex_nodes(repo_path, mg, top_n, user_clearance)

    sections.append(f"## 🔥 Top {top_n} Highest-Complexity Functions\n")
    sections.append(
        "_Ranked by outgoing `CALLS` edges (blast radius). "
        "These are the highest architectural risk points in the codebase._\n\n"
    )

    call_graph_sections = []
    for i, node in enumerate(top_nodes, 1):
        name = node.get("name", "unknown")
        fp = node.get("file_path", "?")
        calls = node.get("call_count", 0)
        rel_path = fp.replace(str(repo_path) + "/", "")

        sections.append(
            f"**{i}. `{name}`** — {calls} outgoing calls  \n" f"`{rel_path}`\n\n"
        )
        call_graph_sections.append((name, fp, node))

    sections.append("---\n")

    # ── 4. Execution Trace Summaries ─────────────────────────
    sections.append("## 📊 Execution Trace Summaries\n")
    for name, fp, node in call_graph_sections:
        sections.append(f"### `{name}`\n")
        sections.append(
            explain_call_graph(
                name, mg, groq_client, depth=2, user_clearance=user_clearance
            )
        )
        sections.append("\n\n")
    sections.append("---\n")

    # ── 5. ADRs (Groq narration per top-N function) ───────────────
    logger.info("wiki_building_adrs", top_n=top_n)
    sections.append("## 📝 Architectural Decision Records (ADRs)\n")
    sections.append(
        "_AI-narrated ADRs for the highest-complexity functions, "
        "grounded in the Memgraph structural context._\n\n"
    )

    from dev_guardian.graphrag.hybrid_retriever import HybridRetriever

    retriever = HybridRetriever(memgraph=mg)

    for node in top_nodes:
        name = node.get("name", "unknown")
        fp = node.get("file_path", "?")
        start_line = node.get("start_line") or 1
        end_line = node.get("end_line") or start_line + 30

        # Read source from disk
        try:
            src_lines = (
                Path(fp).read_text(encoding="utf-8", errors="replace").splitlines()
            )
            source = "\n".join(src_lines[max(0, start_line - 1) : end_line])
        except (OSError, IOError):
            source = f"# Source not readable for {name}"

        # Pull structural context for this node from Memgraph
        try:
            graph_result = retriever.retrieve(
                query=name, user_clearance=user_clearance, top_k=5
            )
            context = graph_result.get("merged_context", "")
        except Exception:
            context = "(Graph context unavailable)"

        adr = generate_adr(
            node_name=name,
            node_source=source,
            graphrag_context=context,
            groq_client=groq_client,
        )
        sections.append(adr + "\n")

    sections.append("---\n\n_End of Guardian Wiki_\n")

    logger.info("wiki_built", sections=len(sections))
    return "\n".join(sections)


def save_wiki(content: str, output_path: Path) -> Path:
    """
    Write the wiki content to disk.

    Args:
        content: Markdown wiki string.
        output_path: Target file path (e.g. Path("GUARDIAN_WIKI.md")).

    Returns:
        The resolved output path.
    """
    output_path.write_text(content, encoding="utf-8")
    logger.info("wiki_saved", path=str(output_path))
    return output_path.resolve()
